// action type 
export const ADD_PRODUCT= "ADD_PRODUCT"
export const GET_PRODUCT= "GET_PRODUCT"
export const ADD_TO_CART= "ADD_TO_CART"
export const INCREMENT_CART= "INCREMENT_CART"
export const DECREMENT_CART= "DECREMENT_CART"
export const INCREMENT_STOCK= "INCREMENT_STOCK"
export const DECREMENT_STOCK= "DECREMENT_STOCK"
